sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: DOgKA3mLMlPVf5wSL8Whhe5x16wnMa2IGxEEjFoUZMtDUK3AHRDZgX/T/TBBcwKcvdCpUF+mwLL71Zdk+PwAp3N1/dyLmutvJ5O5CSXW1gMoTdPnzzaUSJMLleCBNA1arPDzP9EHql4zSJLNaJbIeVrmeXVsAfhH3J+fSlDaJaWqapA5oPoZC7q0rXjQdYUjBzvOLkjj+xhmDicoJUf0OZabJIXq6fidO4plY5gszXBJIH/nGa0e3vklVGzUPOp/phhLKz/TSAQ0F/UU54fWKuPtn0nakwzQxQdr/z4k4JN/cb1EvCRiw1JI+aZCLEZd+gmm7ZxNKpqU+gCF8Xp/FlI41AptpVlcxurrksJZ/FlQ4FySkUZ45wQhp/oJvBwLLd37pzxGOtc5NlYV/odJYMeiN2E5LSf4DC3U1IDHA6entS/t475cqUshLyYuA8SkBwuaTf27vnzc+n6Jh+ko3QatbcqDgepDwqOkZIGp7d3LLtIbEswWsIf4kkGN3NsDu1faiyAYFS/9ZQ6K5WHYkr0giwToilDRUulYErqClqw67NH+GRz9+Fhz9RjwVWgpGQiyUXupthsSw1Fe3dRtkMERTlBoYilOv6rLHRHLGeMwGfQnGt4S1VpcItmB2cwREmy1l4nAdAXHSw9mugLC7Le0LhOEE3oKBwyi3MPfXwU=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Devil-s-Paw_2767
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy